### PR TITLE
Add support for shared_ptr with polymorphism

### PR DESCRIPTION
**Pull request by scgroot**
See issue #54

### CODE REVIEW

**Comment by mjkl-gh** [comment]
@Loki-Astari is it possible to merge this MR? I'm currently in need of this functionality

**Comment by Loki-Astari** [comment]
This is an old one and a lot has changed.

Note: The functionality for std::unique_ptr already exists.
          I have added the functionality for std::shared_ptr (but you need to define SCGRROT_SHARED_PTR_SUPPRT)
          See: src/Serialize/Traits.h

This is now in the master branch.
I am getting this published on brew now (but that usually takes a few days).

**Comment by Loki-Astari** [comment]
This code has been merged into master.
Define 'SCGRROT_SHARED_PTR_SUPPRT' in your build tools to activate the functionality.

**Comment by Loki-Astari** [comment]
Code now available via homebrew as well.

**Comment by Loki-Astari** [comment]
https://github.com/Homebrew/homebrew-core/pull/135316

**Pull request closed without merging**
